# Generated by Django 5.2.8 on 2025-11-20 18:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('defect_type', models.CharField(choices=[('color_variation', 'Color Variation'), ('fabric_flaw', 'Fabric Flaw'), ('stitching_issue', 'Stitching Issue'), ('dimensional_deviation', 'Dimensional Deviation'), ('printing_defect', 'Printing Defect'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=10)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('production_batch_id', models.CharField(max_length=100)),
                ('ml_flag', models.BooleanField(default=False)),
                ('ml_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Defect Log',
                'verbose_name_plural': 'Defect Logs',
                'db_table': 'quality_defect_log',
            },
        ),
    ]
