# Generated by Django 5.2.8 on 2025-11-20 18:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM'), ('rf', 'Random Forest'), ('lr', 'Logistic Regression'), ('svm', 'Support Vector Machine'), ('cnn', 'Convolutional Neural Network')], max_length=10)),
                ('version', models.CharField(max_length=20)),
                ('path_on_disk', models.CharField(max_length=255)),
                ('metrics_json', models.TextField(blank=True, null=True)),
                ('last_trained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Model Metadata',
                'verbose_name_plural': 'ML Model Metadata',
                'db_table': 'mlservice_modelmeta',
            },
        ),
    ]
